### ISSUE TITLE
服务端日志里有错误

### ISSUE THREAD

**Issue by bluehj777** [shirakun/ServerStatus#1]
安装后，启动客户端，tmp里的日志看上去没有问题，按频率有数据开始更新
在服务端，好像不工作，刷新http://x.x.x.x/api.php 不显示接收的变化数据，apache的php日志有如下错误

PHP Warning:  file_put_contents(): Filename cannot be empty in /var/www/html/ServerStatus/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 86
PHP Warning:  mkdir(): Permission denied in /var/www/html/ServerStatus/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 316

**Comment by shirakun** [comment]
Hi
Fixed.
Please try again.
