### ISSUE TITLE
apache日志还是有错误RWFileCache.php 无法创建cache文件

### ISSUE THREAD

**Issue by bluehj777** [shirakun/ServerStatus#2]
composer从bullseye源里安装的 composer (2.0.9-2)
然后在/var/www/html/ServerStatus下执行
composer install
修改客户端py的URL 指向
http://192.168.100.234/ServerStatus/public/api.php
客户端py运行正常，有数据输出
但是刷新http://192.168.100.234/ServerStatus/public/api.php依然看不到变化
apache日志：
PHP Warning: file_put_contents(): Filename cannot be empty in /var/www/html/ServerStatus/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 86
PHP Warning: mkdir(): Permission denied in /var/www/html/ServerStatus/vendor/rapidwebltd/rw-file-cache/src/RWFileCache.php on line 316

**Comment by shirakun** [comment]
Please check the permission settings for files and directories
api.php needs permission to read the files in vendor and node.php
Also make sure api.php can read and write to the cache folder of the parent directory

**Comment by bluehj777** [comment]
> Please check the permission settings for files and directories
> api.php needs permission to read the files in vendor and node.php
> Also make sure api.php can read and write to the cache folder of the parent directory

嗯，没啥大问题了，是权限问题。
还有点小瑕疵，如果监控服务器不超过一天，日志会有错误
PHP Notice:  Undefined variable: days_num in /var/www/html/ServerStatus/public/api.php on line 19, referer: http://192.168.100.123/ServerStatus/public/index.htm

**Comment by shirakun** [comment]
fixed

**Comment by bluehj777** [comment]
好像应该只添加
    $days_num = 0; 
即可
否则前端总是显示 0小时0分0秒
